name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Sync to Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: zhannakakenova/my-gradio-app
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: gradio
